### ISSUE TITLE
Example on https://bitmovin.com/demos/custom-adaptation doesn't work

### ISSUE THREAD

**Issue by kpandroid** [bitmovin/demos#42]

**Comment by lukaskroepfl** [comment]
Hello!

This repository is not meant to be used for local development but serves as source for the code samples shown at [bitmovin.com/demos](https://bitmovin.com/demos/). How to get started with the players is shown in our [docs](https://bitmovin.com/docs/getting-started) or [dashboard](https://bitmovin.com/dashboard). If you need help please refer to the support section in our dashboard. 🙂
