### ISSUE TITLE
Unable to run demo

### ISSUE THREAD

**Issue by marcoponta** [bitmovin/demos#45]
Please, verify the demo or detail the steps to make it work.
Project is interesting but without being able to test it...
Thank you

**Comment by lukaskroepfl** [comment]
Hello!

This repository is not meant to be used for local development but serves as source for the code samples shown at [bitmovin.com/demos](https://bitmovin.com/demos/). How to get started with the players is shown in our [docs](https://bitmovin.com/docs/getting-started) or [dashboard](https://bitmovin.com/dashboard). If you need help please refer to the support section in our dashboard. 🙂
