### ISSUE TITLE
Widevine license server not available

### ISSUE THREAD

**Issue by mauro1855** [bitmovin/demos#88]
Hi,

Seems like the widevine license server is not working correctly for the DRM example.
https://widevine-proxy.appspot.com/proxy returns 404.

Can you take a look or find an alternative?

![image](https://user-images.githubusercontent.com/18258655/171828005-0715d6a1-918b-4c7e-960a-17a66edda968.png)

Best regards,
Mauro

**Comment by dweinber** [comment]
Hey @mauro1855, thanks for letting us know. I'm happy to let you know that this got fixed already.
